import { Modal } from './ui/modal'
// Brand mark - same asset App.tsx + AppSettings use. Generated by
// `pnpm --filter @kanbini/desktop run build:icons` (ADR-0051).
import brandLogo from '../assets/logo.png'

// M5-B first-run welcome screen (ADR-0049). Shows once, on the very
// first launch after install (or after the user wipes
// `localStorage['kanbini.settings']` - same recovery path as any
// other renderer-only preference). Dismissal sets
// `settings.hasSeenWelcome = true`, which the App-level effect
// persists; future launches skip the modal silently.
//
// Copy intentionally light: this is the "welcome to your new local
// kanban app" intro, not a feature tour. The boards-home renders
// behind the backdrop so a returning user (e.g. wiped userData) sees
// their familiar surface the instant they dismiss. Sample-data seed
// in main pre-populates a Welcome Board, so the empty state isn't
// what users see here.

export function WelcomeModal({
  open,
  onDismiss
}: {
  open: boolean
  onDismiss: () => void
}) {
  return (
    <Modal open={open} onClose={onDismiss} label="Welcome to Kanbini">
      <div className="flex flex-col gap-5 p-6">
        <img
          src={brandLogo}
          alt=""
          aria-hidden
          className="size-16 self-center shrink-0"
          draggable={false}
        />
        <div className="flex flex-col gap-2">
          <h2 className="text-xl font-semibold">Welcome to Kanbini</h2>
          <p className="text-sm text-muted-foreground">
            A local-first kanban for one. Your boards, lists, and
            cards live in a single SQLite file under your user data
            folder, nothing leaves your machine unless you opt in.
          </p>
        </div>

        <ul className="flex flex-col gap-2 text-sm">
          <WelcomeRow
            title="Offline by default"
            body="No accounts, no telemetry, no auto-update pings."
          />
          <WelcomeRow
            title="Backups you control"
            body="Settings → Backup & restore exports a plain-text snapshot of everything (also runs on quit)."
          />
          <WelcomeRow
            title="Opt-in connections"
            body="Link previews, an Obsidian one-way push, and a local MCP channel so an AI can drive the board live, all off by default."
          />
        </ul>

        <p className="text-xs text-muted-foreground">
          We pre-seeded a Welcome Board so you can poke around. Open
          it from the home picker behind this dialog, or click
          {' '}<strong>+ New board</strong>{' '}
          to start fresh.
        </p>

        <div className="flex justify-end">
          {/* "Got it" rather than "Get started" - the button just
              dismisses the modal so the user can act on the copy
              above. A CTA verb here promises an action this button
              doesn't actually take (no tour, no navigation). */}
          <button
            type="button"
            onClick={onDismiss}
            className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background"
          >
            Got it
          </button>
        </div>
      </div>
    </Modal>
  )
}

function WelcomeRow({ title, body }: { title: string; body: string }) {
  return (
    <li className="flex flex-col gap-0.5 rounded-md border border-border p-3">
      <span className="font-medium text-foreground">{title}</span>
      <span className="text-xs text-muted-foreground">{body}</span>
    </li>
  )
}
